### ISSUE TITLE
Create first release & tags

### ISSUE THREAD

**Issue by Legmo** [Legmo/hotquotes#16]
**Subtasks**
- [x] Decide on a release numbering scheme
- [x]  Create Protected tags rules
- [x] Create first release
- [x] Create first tag `v0.1`

**Links**
- https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
- https://github.com/Legmo/hotquotes/tags
- https://ru.wikipedia.org/wiki/%D0%9D%D1%83%D0%BC%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D1%8F
<br>
